{
  outDir: '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/lib-es6/',
  rootDir: '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/src',
  allowSyntheticDefaultImports: true,
  esModuleInterop: true,
  importHelpers: true,
  allowJs: true,
  declaration: false,
  emitDecoratorMetadata: true,
  experimentalDecorators: true,
  lib: [ 'lib.esnext.d.ts' ],
  skipLibCheck: true,
  moduleResolution: 99,
  sourceMap: true,
  traceResolution: false,
  baseUrl: '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/node_modules/@upradata/heft-node-rig/profiles/default',
  forceConsistentCasingInFileNames: true,
  jsx: 2,
  declarationMap: false,
  inlineSources: true,
  strictBindCallApply: true,
  strictFunctionTypes: true,
  strictNullChecks: true,
  strictPropertyInitialization: false,
  useUnknownInCatchVariables: false,
  noEmitOnError: false,
  allowUnreachableCode: false,
  typeRoots: [
    '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/node_modules/@types',
    '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/node_modules/@upradata/heft-node-rig/node_modules/@types'
  ],
  module: 1,
  incremental: true,
  target: 2,
  configFilePath: '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/tsconfig.json',
  tsBuildInfoFile: '/home/milottit/Libraries/Upra-Data/monorepo/libraries/node/cache/temp/build.typescript/ts_Kqe8CQZv.json'
}